#
# This is used by ./rdev.sh to manage the various robotpy packages
#
# allwpilib-based python wheel versioning is xxxx.x.x.y:
# - x is the upstream version
# - y are specific robotpy patches when we release out of band
#
# Beta releases are always YEAR.0.0bX[.postX]
#

[py_versions]

# Usually the same as wpilib_bin_version
native = "2027.0.0a2"

# Will eventually sync with native
halsim_native = "2027.0.0a2"

# Usually similar to native, but subminor version is bumped for bugfixes
# - ./rdev.sh ci check_tag will fail if this doesn't match current tag
wrapper = "2027.0.0a2"

[params]

wpilib_bin_version = "2027.0.0-alpha-2"
wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/release-2027"
# wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/development-2027"

# Don't update these maven artifacts
exclude_artifacts = [
    "opencv-cpp"
]

robot_wheel_platform = "linux-systemcore"

[params.requirements]
semiwrap = "~=0.1.4"
hatch-meson = "~=0.1.0b2"
hatch-nativelib = "~=0.2.0"
hatch-robotpy = "~=0.2.1"


[subprojects."robotpy-native-wpiutil"]
py_version = "native"
robot = true

[subprojects."robotpy-native-datalog"]
py_version = "native"
robot = true

[subprojects."robotpy-native-wpinet"]
py_version = "native"
robot = true

[subprojects."robotpy-native-ntcore"]
py_version = "native"
robot = true

[subprojects."robotpy-native-wpihal"]
py_version = "native"
robot = true

[subprojects."robotpy-native-wpimath"]
py_version = "native"
robot = true

[subprojects."robotpy-native-apriltag"]
py_version = "native"
robot = true

[subprojects."robotpy-native-wpilib"]
py_version = "native"
robot = true

[subprojects."robotpy-native-romi"]
py_version = "native"
robot = false

[subprojects."robotpy-native-xrp"]
py_version = "native"
robot = false

[subprojects."robotpy-wpiutil"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-wpilog"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-wpinet"]
py_version = "wrapper"
robot = true

[subprojects."pyntcore"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-hal"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-wpimath"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-cscore"]
py_version = "wrapper"
robot = true

# practicality over purity - this is because we use a static
# library that only exists at build time
ci_scan_headers = false
ci_update_yaml = false

[subprojects."robotpy-apriltag"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-wpilib"]
py_version = "wrapper"
robot = true

[subprojects."robotpy-halsim-ds-socket"]
py_version = "halsim_native"
robot = false

[subprojects."robotpy-halsim-ws"]
py_version = "halsim_native"
robot = false

[subprojects."robotpy-halsim-gui"]
py_version = "wrapper"
robot = false

[subprojects."robotpy-romi"]
py_version = "wrapper"
robot = false

[subprojects."robotpy-xrp"]
py_version = "wrapper"
robot = false
