#
# This is used by ./rdev.sh to manage the various robotpy packages
#
# allwpilib-based python wheel versioning is xxxx.x.x.y:
# - x is the upstream version
# - y are specific robotpy patches when we release out of band
#
# Beta releases are always YEAR.0.0bX[.postX]
#

[py_versions]

# Usually the same as wpilib_bin_version
native = "2025.3.2"

# Will eventually sync with native
halsim_native = "2025.3.2.2"

# Usually similar to native, but subminor version is bumped for bugfixes
wrapper = "2025.3.2.2"

[params]

wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/release"
wpilib_bin_version = "2025.3.2"
#wpilib_bin_url = "https://frcmaven.wpi.edu/artifactory/development"

# Don't update these maven artifacts
exclude_artifacts = [
    "opencv-cpp"
]

[params.requirements]
semiwrap = "~=0.1.2"
hatch-meson = "~=0.1.0b2"
hatch-nativelib = "~=0.2.0"
hatch-robotpy = "~=0.2"


[subprojects."robotpy-native-wpiutil"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-wpinet"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-ntcore"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-wpihal"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-wpimath"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-apriltag"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-wpilib"]
py_version = "native"
roborio = true

[subprojects."robotpy-native-romi"]
py_version = "native"
roborio = false

[subprojects."robotpy-native-xrp"]
py_version = "native"
roborio = false

[subprojects."robotpy-wpiutil"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-wpinet"]
py_version = "wrapper"
roborio = true

[subprojects."pyntcore"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-hal"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-wpimath"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-cscore"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-apriltag"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-wpilib"]
py_version = "wrapper"
roborio = true

[subprojects."robotpy-halsim-ds-socket"]
py_version = "halsim_native"
roborio = false

[subprojects."robotpy-halsim-ws"]
py_version = "halsim_native"
roborio = false

[subprojects."robotpy-halsim-gui"]
py_version = "wrapper"
roborio = false

[subprojects."robotpy-romi"]
py_version = "wrapper"
roborio = false

[subprojects."robotpy-xrp"]
py_version = "wrapper"
roborio = false
