---
name: bazel

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Build allowing failure
        run: bazel test //... -k --config=build_buddy || true

      - name: Hack modify semiwrap
        run: python3 -m bazel_scripts.debug.HACK_fix_pypi

      - name: Build again
        run: bazel test //... -k --config=build_buddy
