---
name: bazel

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Build allowing failure # TODO(PJ) Mac seems flakey on github. Turning it off for now
        run: bazel test //... -k --config=build_buddy
