---
name: bazel

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        # python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        python_version: ["3.11"]
    runs-on: ${{ matrix.platform }}
    env:
      BAZEL_PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with: { python-version: '3.10' }

      - name: HACK build
        run: bazel test //subprojects/robotpy-wpiutil/tests:test_struct --config=build_buddy || true

      - name: Hack modify semiwrap
        run: python3 -m bazel_scripts.debug.HACK_fix_pypi
  
      - name: First build pass again
        run: bazel test //... -k --config=build_buddy || true

      - name: Build again (gets better signal on failures)
        run: bazel test //... -k --config=build_buddy
