name: Bazel

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-14    
          - windows-2022
        python_version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Fix Python Version
        run: sed -i -e "s/PYTHON_VERSION = .*/PYTHON_VERSION = '${{ matrix.python_version }}'/" WORKSPACE

      - name: Run requirements update
        run: bazel run //bazel_utils/requirements/${{ matrix.python_version }}:requirements.update
        if: matrix.os != 'windows-2022'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} ${{ matrix.python_version }} Requirements
          path: bazel_utils/requirements/${{ matrix.python_version }}/requirements_linux.txt
        if: matrix.os == 'ubuntu-22.04'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} ${{ matrix.python_version }} Requirements
          path: bazel_utils/requirements/${{ matrix.python_version }}/requirements_osx.txt
        if: matrix.os == 'macos-14'

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Merge Requirements
        uses: actions/upload-artifact/merge@v4
        with:
          name: Requirements
          pattern: "* Requirements"
          delete-merged: true