
name: Push to allwpilib

on:
  workflow_dispatch:
  push:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Download copybara
        run: |
          wget https://github.com/google/copybara/releases/download/v20250616/copybara_deploy.jar
          chmod +x copybara_deploy.jar
        
      - name: Run copybara
        run: java -jar copybara_deploy.jar mostrobotpy_to_allwpilib
